name: daos_server
access_points: ['localhost']
transport_config:
  allow_insecure: true
  client_cert_dir: /etc/daos/certs/clients
  ca_cert: /etc/daos/certs/daosCA.crt
  cert: /etc/daos/certs/server.crt
  key: /etc/daos/certs/server.key
nr_hugepages: 512
provider: ofi+sockets
control_log_file: /tmp/daos_server.log
engines:
-
  targets: 1
  nr_xs_helpers: 0
  first_core: 0
  fabric_iface: eth0
  fabric_iface_port: 31416
  log_file: /tmp/daos_engine.0.log
  env_vars:
  - FI_SOCKETS_MAX_CONN_RETRY=1
  - FI_SOCKETS_CONN_TIMEOUT=2000

  scm_mount: /mnt/daos    # map to -s /mnt/daos
  scm_class: ram
  scm_size: 4

  bdev_class: file
  bdev_size: 5
  bdev_list: [/tmp/daos-bdev]
  